import Providers from "@/context/Providers"
import { Inter } from "next/font/google";
import "../styles/main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "shaibu mansour",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers
        attribute="className"
        defaultTheme="system"
        enableSystem={true}
        disableTransitionOnChange
        >
        {children}
        </Providers>
        </body>
    </html>
  );
}
